    name: Playwright Tests
    on:
        push:
            branches: [main]
    jobs:
        playwrighttests:
            runs-on: ubuntu-latest
            container:
                image: mcr.microsoft.com/playwright:v1.36.2-focal
                env:
                    ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
            steps:
                - name: Checkout repository
                  uses: actions/checkout@v2
                - name: Run tests
                  run: |
                    echo "Start the shoppong store application"
                    ./shopping-store-linux-amd64.sh &
                    echo "Install dependecis from lockfile"
                    npm ci
                    echo "Run Playwright tests"
                    npm run test:ci
